### ISSUE TITLE
We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like CompVis/stable-diffusion-safety-checker is not the path to a directory containing a config.json file. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'

### ISSUE THREAD

**Issue by LKJ-np** [yunqing-me/AttackVLM#1]
您好，关于这个模型我应该去哪里下载呢？您这个步骤里面没有说明。希望您看到能给我指点下，谢谢。

**Comment by yunqing-me** [comment]
Hi, thank you for your interest in our work.

Could you please provide the necessary steps to reproduce the error?

**Comment by LKJ-np** [comment]
> 您好，感谢您对我们工作的兴趣。
> 
> 您能否提供重现该错误所需的步骤？

conda env create -f environment.yaml
conda activate ldm
git clone https://github.com/CompVis/stable-diffusion.git
cd stable-diffusion
download https://drive.google.com/file/d/19tT036LBvqYonzI7PfU9qVi3jVGApKrg/view?usp=sharing
![image](https://github.com/yunqing-me/AttackVLM/assets/71888905/9d8ef21e-df96-4b27-aec7-f4c770e034ba)
![image](https://github.com/yunqing-me/AttackVLM/assets/71888905/29d079fe-2afc-4c27-b005-2348f99a40e9)
Where can I download the line drawing model?
python ./scripts/txt2img.py \
        --ddim_eta 0.0 \
        --n_samples 10 \
        --n_iter 1 \
        --scale 7.5 \
        --ddim_steps 50 \
        --plms \
        --skip_grid \
        --ckpt ./_model_pool/sd-v1-4-full-ema.ckpt \
        --from-file '/root/wellmed/wellmed-pt/AttackVLM-main/stable-diffusion/coco_captions.txt' \
        --outdir '/root/wellmed/wellmed-pt/AttackVLM-main/stable-diffusion/images' \
The above are my steps. Without the model, this error occurs.

**Comment by yunqing-me** [comment]
Hi, 

Thank you for the information. 

We use the pretrained ckpt provided by [Stable-Diffusion-v1](https://github.com/CompVis/stable-diffusion#weights:~:text=The%20weights%20are%20available%20via), the weights can be downloaded here: [sd-v1-4-full-ema.ckpt](https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4-full-ema.ckpt).

We will update the repo soon for clarification. Thanks again for pointing out this :)

**Comment by LKJ-np** [comment]
> Hi,
> 
> Thank you for the information.
> 
> We use the pretrained ckpt provided by [Stable-Diffusion-v1](https://github.com/CompVis/stable-diffusion#weights:~:text=The%20weights%20are%20available%20via), the weights can be downloaded here: [sd-v1-4-full-ema.ckpt](https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4-full-ema.ckpt).
> 
> We will update the repo soon for clarification. Thanks again for pointing out this :)

Hello, sorry to bother you again, I downloaded this ckpt, but there is no model, no json weight error, if it is convenient for you, could you update the detailed deployment process? Or if the deployment is successful, I can write a plan of the deployment process for you and subsequent workers to read. Thank you again for taking time to answer my questions.
![图片](https://github.com/yunqing-me/AttackVLM/assets/71888905/e75507ea-add7-4811-8e5e-031dbaecb98a)

**Comment by yunqing-me** [comment]
Hi, 

Based on my implementation, I found there is no issue of this official ckpt. 
Nevertheless, I have adjusted the ReadME file and you can use the updated one for another test.

I remark that we follow the official stable-diffusion pipeline for generation, therefore it should be a standard process. Please let me know if you still encounter those errors, and I will do a test from scratch.

Thanks a lot for your interest and support.

**Comment by LKJ-np** [comment]
Okay, thank you again for your answer. The email I sent you at 10:48 today contains my confusion. If you have time, you can help me answer it. Thank you again.
