### ISSUE TITLE
Regarding data path in LAVIS

### ISSUE THREAD

**Issue by 18445864529** [yunqing-me/AttackVLM#11]
Thank you for the great work.
I'd like to know more details about the data preparation for the `train_adv_img_query` experiment. i.e. the `vit_adv_data` `adv_vit_text_path` `tgt_text_path` variables. 
Currently, they are pointing to the `../output_img` `../output_text` folders by default which are not provided in the repo, nor is there any instruction in the README. 
In my case I want to use the COCO dataset, could you please provide more details about the preparation of these data? Thanks.

(update: after reading through the paper and the code, I managed to configure the data and the training. But I would certainly look forward to the official release of the code that reproduces the LVLM experiments)

**Comment by 18445864529** [comment]
Similarly for the MiniGPT4 experiment `FileNotFoundError: [Errno 2] No such file or directory: '../_output_img/minigpt4_trans'`, what should I put here? Should it be the same image folder for `minigpt4_trans` and `blip_trans` or should they be produced using some script with a certain data structure/format? Thanks again in advance.

**Comment by yunqing-me** [comment]
Hi, thank you for your interest in our work.

I am still cleaning the code and updating the repo. I will consider your comments in future updates, thanks!
