### ISSUE TITLE
dimension mismatch in code

### ISSUE THREAD

**Issue by 18445864529** [yunqing-me/AttackVLM#12]
Take the MiniGPT-4 query experiment for example 
at L250: `adv_text_feature` has a shape of the 0-th dimension being the batch size (e.g. 10)
https://github.com/yunqing-me/AttackVLM/blob/9494be851029ff72b375f3cad1edefb022d4c6e8/MiniGPT-4/_train_adv_img_query.py#L250

while at L281-287: `text_of_perturbed_imgs` has a shape of the 0-th dimension being the num query*batch size (e.g. 200)
 https://github.com/yunqing-me/AttackVLM/blob/9494be851029ff72b375f3cad1edefb022d4c6e8/MiniGPT-4/_train_adv_img_query.py#L281-L287

Thus subtracting these two tensors would cause an error at L300: 
https://github.com/yunqing-me/AttackVLM/blob/9494be851029ff72b375f3cad1edefb022d4c6e8/MiniGPT-4/_train_adv_img_query.py#L300

Is this a bug in the code? To solve this, should I repeat `adv_text_feature` 20 times? Thanks.

**Comment by yunqing-me** [comment]
Hi, perhaps you can set `batch_size=1`?

**Comment by 18445864529** [comment]
Thanks. Speaking of which I would also like to know how to do batch inference with MiniGPT-4? Since the inference part functions are still missing in the code, I implemented by myself but can only do bsz=1 inference, while bsz>1 will trigger the cuda assertion error like mentioned in https://github.com/Vision-CAIR/MiniGPT-4/issues/268

**Comment by yunqing-me** [comment]
Thanks, the same here, I tried but cannot do batch inference.
