### ISSUE TITLE
Where are the implementations of MF-it?

### ISSUE THREAD

**Issue by yechao-zhang** [yunqing-me/AttackVLM#16]
It seems like your code only implements the MF-ii attack.  The MF-it attack has much better ASRs according to your paper.

**Comment by yunqing-me** [comment]
Thank you for the interest. Would like to clarify that MF-it _only_ obtains higher clip-score (computed on features) in Table-1, but it did not lead to a better results in all other more important experiments. See Sec. 4.2 ```Surprisingly, we find that MF-it performs worse than MF-ii``` and Table-2 comparison for more details. Therefore, we provided the example code of MF-ii and MF-it, which are essential components to achieve a overall good results.
