### ISSUE TITLE
Blip2OPT' object has no attribute 'forward_encoder_image' 

### ISSUE THREAD

**Issue by klea-ziu** [yunqing-me/AttackVLM#17]
For the transfer attack implemented in the script LAVIS_tool/_train_adv_img_blip.py, the target image features come from the function where blip_model is loaded through lavis package. However, it seems like there is no implementation of the forward_encoder_image function in the source code of lavis, thus triggering the error: AttributeError: 'Blip2OPT' object has no attribute 'forward_encoder_image'. How to solve this issue?

**Comment by yukodada** [comment]
bro， do u solve it?

**Comment by yunqing-me** [comment]
Thanks for your interest. This forward function was adapted from the original implementation and one can follow this: [blip2opt_forward](https://github.com/salesforce/LAVIS/blob/506965b9c4a18c1e565bd32acaccabe0198433f7/lavis/models/blip2_models/blip2_opt.py#L107)
