### ISSUE TITLE
What models are used for img2prompt and LLAVA

### ISSUE THREAD

**Issue by klea-ziu** [yunqing-me/AttackVLM#18]
Hello, 
Thank you for the provided code. I was reading the paper and checking the GitHub as well but there are no implementation details regarding img2prompt and LLAVA models. Can you please elaborate more and share the details of how can we reproduce these models? 
Thank you in advance.

**Comment by sftsgly** [comment]
bro，do u solve it？

**Comment by yukodada** [comment]
bro, solved it?

**Comment by sftsgly** [comment]
I check the lavis and find that img2prompt only have base type now , so I use this model type and code some function by myself to sove it.

**Comment by yunqing-me** [comment]
Thanks for the interest. 
- For llava, please refer to the official installation: https://github.com/haotian-liu/LLaVA?tab=readme-ov-file#install
- For img2prompt, please refer to the base (standard) type implementation of their code: https://github.com/salesforce/LAVIS/blob/main/lavis/models/img2prompt_models/img2prompt_vqa.py

**Comment by sftsgly** [comment]
thanks
