### ISSUE TITLE
data question

### ISSUE THREAD

**Issue by LKJ-np** [yunqing-me/AttackVLM#2]
![image](https://github.com/yunqing-me/AttackVLM/assets/71888905/2c318454-8a03-4f54-930a-be63643b2895)
What is the dataset for cle_data_path? Did you find it yourself?I have run through the stable-diffusion of the data set of tgt_data_path, explaining stable-diffusion no problem,Is the coco dataset run by stable-diffusion 10, 100, 10000 or all of them?
Thank you very much if you have time to answer my question.

**Comment by LKJ-np** [comment]
I found the ImageNet-1K dataset. I need to randomly select 5w pictures from it as the cle image dataset or is there a fixed dataset?

**Comment by yunqing-me** [comment]
Thank you for the interest in our work.

`--cle_data_path` indicates the clean images that will be attacked. It should be a normal directory that contains sub-folder(s).

`--tgt_data_path` indicates the target images that will be used to attack the clean images. It should be a normal directory that contains sub-folder(s). 

This script aims to support the large-scale training/attack and you can use any dataset you want that meets the general dataset format (see our [definition of a dataset](https://github.com/yunqing-me/AttackVLM/blob/b8157d872efc551ee0bbbca2be838b679c6adccc/unidiff_tool/_train_adv_img.py#L43C27-L43C27)).

**Comment by LKJ-np** [comment]
Ok, thank you very much. I copied your code. I would like to ask what data set is used to score CLIP obtained by using different attack countermeasure methods in your paper? Is cle_data the 50k images in the ImageNet-1K dataset? Is tgt_data coco_captions.txt or coco_captions_10.txt, coco_captions_100.txt, coco_captions_10000.txt? Could you please inform me so that I can reproduce your paper?

**Comment by yunqing-me** [comment]
Thanks for your information.

We used the 50k validation images from ImageNet-1K as cle_data; We used 50k tgt_data generated by Stable-Diffusion from coco_captions. In this way, there is a tgt_data for each cle_data. 

In practice, we find that using 10k validation images and 10k tgt_data is sufficient to get very close results, with a relatively lower computation bandwidth. Therefore, we may suggest you to use the 10k validation images and the released coco_captions_10000.txt in the experiment first. We will release more config files / processed files in the upcoming updates.

**Comment by LKJ-np** [comment]
Hello,I would like to ask if you can provide a copy of the code reproduced by other VLM models? I have reproduced the evaluation of UniDiffuser, but other BLIP, BLIP-2, MiniGPT-4, etc. have not yet reproduced.
Can these adversarial attacks of VLM model and the code of Tusson be shared with me? I want to reproduce this form, if it is inconvenient to share, could you please explain to me in detail how to reproduce other VLM models, because at present, I only follow the result of UniDiffuser reproduced on GitHub, and I don't know how to reproduce others, could you please give me some Pointers? Thank you very much.
Thank you for taking the time to answer my question, thank you.
