### ISSUE TITLE
GradCAM Visualization

### ISSUE THREAD

**Issue by jdg900** [yunqing-me/AttackVLM#21]
Hello.

Thank you for sharing your nice work!

I wonder how you visualized the GradCAM in Figure 8.

Could you share the visualization code?

I'm looking forward to hearing you!

**Comment by yunqing-me** [comment]
Hi: Thanks for the interest. To visualize the features related to the text prompt, you can follow this code: 
[visualization-of-features](https://colab.research.google.com/github/salesforce/LAVIS/blob/main/projects/img2llm-vqa/img2llm_vqa.ipynb)
