### ISSUE TITLE
Minigpt4 code problerm

### ISSUE THREAD

**Issue by returnaaa** [yunqing-me/AttackVLM#22]
I can not understand why size=(batch_size, 577, 768), in vit , the size = (batch_size, 257, 1408), in vit and q-former , the size = (batch_size, 32, 768)
![image](https://github.com/user-attachments/assets/8c386ac4-90a8-4caa-abe5-12ee2105a36b)

**Comment by sftsgly** [comment]
bro , i can't find the function forward_encoder. Do you know how to find it?

**Comment by returnaaa** [comment]
> bro , i can't find the function forward_encoder. Do you know how to find it?
It seems that the author needs to implement it himself, but he doesn't seem to have open sourced it.

**Comment by sftsgly** [comment]
I wrote some code based on the answer function in demo.py to experiment, but the effect was not good.
https://github.com/Vision-CAIR/MiniGPT-4/blob/main/demo.py

**Comment by returnaaa** [comment]
> I wrote some code based on the answer function in demo.py to experiment, but the effect was not good. https://github.com/Vision-CAIR/MiniGPT-4/blob/main/demo.py

hi, bro, Can you share the code you modified, I have doubts about this function

**Comment by sftsgly** [comment]
[Desktop.zip](https://github.com/user-attachments/files/17484521/Desktop.zip)
Here, but in query.py I delete the wandb. And this function can only pass one image at a time.

**Comment by yunqing-me** [comment]
Thanks for the interest. Here it is:
1. ViT (size = batch_size, 577, 768):
- 577 = 1 (CLS token) + 576 (24x24 patches)
- 768 = embedding dimension

2. ViT variant (size = batch_size, 257, 1408):
- 257 = 1 (CLS token) + 256 (16x16 patches)
- 1408 = larger embedding dimension

3. Q-Former (size = batch_size, 32, 768):
- 32 = number of learnable query tokens
- 768 = embedding dimension matching BERT/other models

The differences come from:
- Different patch sizes affecting sequence length
- Model-specific embedding dimensions
- Q-Former using fixed number of queries vs. image-dependent patches
