### ISSUE TITLE
VLM model

### ISSUE THREAD

**Issue by LKJ-np** [yunqing-me/AttackVLM#4]
Hello, I would like to ask if you can provide a copy of the code reproduced by other VLM models? I have reproduced the evaluation of UniDiffuser, but other BLIP, BLIP-2, MiniGPT-4, etc. have not yet reproduced. Thank you for taking the time to answer my question, thank you.

**Comment by yunqing-me** [comment]
Hi, 
Thank you for your interest in our work.
We will release the entire code in two weeks after some recent ddls, stay tuned!

**Comment by LKJ-np** [comment]
The large model you just updated includes Unidiff, MiniGPT-4 and LAVIS, but it is not mentioned in the LAVIS paper. I would like to ask what model this is, and how to reproduce several large models in the paper?For example, BLIP, BLIP2, etc.
![image](https://github.com/yunqing-me/AttackVLM/assets/71888905/19706dcd-8a86-4d4e-a6f1-acc98c8f8a3e)
