### ISSUE TITLE
The large model you just updated includes Unidiff, MiniGPT-4 and LAVIS, but it is not mentioned in the LAVIS paper. I would like to ask what model this is, and how to reproduce several large models in the paper?For example, BLIP, BLIP2, etc.

### ISSUE THREAD

**Issue by LKJ-np** [yunqing-me/AttackVLM#5]
The large model you just updated includes Unidiff, MiniGPT-4 and LAVIS, but it is not mentioned in the LAVIS paper. I would like to ask what model this is, and how to reproduce several large models in the paper?For example, BLIP, BLIP2, etc.
![image](https://github.com/yunqing-me/AttackVLM/assets/71888905/19706dcd-8a86-4d4e-a6f1-acc98c8f8a3e)

_Originally posted by @LKJ-np in https://github.com/yunqing-me/AttackVLM/issues/4#issuecomment-1722234379_

**Comment by yunqing-me** [comment]
The LAVIS lib includes BLIP/BLIP2. We are still cleaning the code and will update the repo progressively.
