### ISSUE TITLE
MiniGPT-4 Code

### ISSUE THREAD

**Issue by LKJ-np** [yunqing-me/AttackVLM#6]
Have you not finished writing the function method? Have I seen the method inside?
![image](https://github.com/yunqing-me/AttackVLM/assets/71888905/df1ba2fe-0b53-4921-ac18-612ba5b0d3b8)
![image](https://github.com/yunqing-me/AttackVLM/assets/71888905/3a352aed-189a-424b-897f-0020dd809164)

**Comment by yunqing-me** [comment]
Thanks for your interest in our work, we are still cleaning the code and will update the repo progressively.
