### ISSUE TITLE
Connot interpret 'torch.float32' as a data type

### ISSUE THREAD

**Issue by LKJ-np** [yunqing-me/AttackVLM#8]
projects/img2llm-vqa/img2llm_vqa.py

resized_img = raw_image.resize((int(w * scaling_factor), int(h * scaling_factor)))
norm_img = np.float32(resized_img) / 255
gradcam = samples['gradcams'].reshape(24,24)
avg_gradcam = getAttMap(norm_img, gradcam, blur=True)
fig, ax = plt.subplots(1, 1, figsize=(5, 5))

The error report points here，Could you please take a look at what the problem is?

**Comment by yunqing-me** [comment]
pyplot is using numpy datatypes to work, you are passing torch datatypes, so you are getting errors.
